# Generated by Django 4.2.4 on 2023-08-17 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import iranian_cities.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("iranian_cities", "0005_auto_20221004_0004"),
        ("salon", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallet",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.AddField(
            model_name="salonimage",
            name="salon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salon_image",
                to="salon.salon",
                verbose_name="سالن",
            ),
        ),
        migrations.AddField(
            model_name="salon",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salon",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="court",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="salon.court",
                verbose_name="نوع زمین ورزشی",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="available_time",
            field=models.ManyToManyField(
                blank=True, to="salon.availabletime", verbose_name="زمان های در دسترس"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="booking_reference",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="salon.bookingreference",
                verbose_name="شماره رزرو",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="court",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="salon.court",
                verbose_name="نوع سالن ورزشی",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="ostan",
            field=iranian_cities.fields.ProvinceField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="iranian_cities.province",
                verbose_name="استان",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="salon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="location",
                to="salon.salon",
                verbose_name="سالن",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="shahrestan",
            field=iranian_cities.fields.CountyField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="iranian_cities.county",
                verbose_name="شهرستان",
            ),
        ),
        migrations.AddField(
            model_name="court",
            name="amenities",
            field=models.ManyToManyField(
                blank=True, to="salon.amenity", verbose_name="امکانات"
            ),
        ),
        migrations.AddField(
            model_name="court",
            name="salon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courts",
                to="salon.salon",
                verbose_name="سالن",
            ),
        ),
        migrations.AddField(
            model_name="court",
            name="size",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="salon.courtsize",
                verbose_name="اندازه",
            ),
        ),
        migrations.AddField(
            model_name="availabletime",
            name="court",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="available_time",
                to="salon.court",
                verbose_name="نوع زمین ورزشی",
            ),
        ),
        migrations.AddField(
            model_name="availabletime",
            name="times",
            field=models.ManyToManyField(
                blank=True, to="salon.timeslot", verbose_name="زمان"
            ),
        ),
        migrations.AddField(
            model_name="amenity",
            name="salon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salon_amenity",
                to="salon.salon",
                verbose_name="سالن",
            ),
        ),
    ]
