# Generated by Django 4.2.4 on 2023-09-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("salon", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amenity",
            name="description",
            field=models.TextField(blank=True, verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="amenity",
            name="icon",
            field=models.ImageField(
                blank=True, upload_to="amenity_icons", verbose_name="ایکون"
            ),
        ),
    ]
