# Generated by Django 4.2.4 on 2023-09-12 06:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("salon", "0002_alter_amenity_description_alter_amenity_icon"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ordertime",
            options={"verbose_name_plural": "تایم های رزروی"},
        ),
    ]
