# Generated by Django 4.2.4 on 2023-08-31 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("salon", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amenity",
            name="updatedAt",
            field=models.DateTimeField(auto_now=True, verbose_name="آپدیت شده در"),
        ),
        migrations.AlterField(
            model_name="availabletime",
            name="updatedAt",
            field=models.DateTimeField(auto_now=True, verbose_name="آپدیت شده در"),
        ),
        migrations.AlterField(
            model_name="bookingreference",
            name="updatedAt",
            field=models.DateTimeField(auto_now=True, verbose_name="آپدیت شده در"),
        ),
        migrations.AlterField(
            model_name="court",
            name="updatedAt",
            field=models.DateTimeField(auto_now=True, verbose_name="آپدیت شده در"),
        ),
        migrations.AlterField(
            model_name="courtsize",
            name="updatedAt",
            field=models.DateTimeField(auto_now=True, verbose_name="آپدیت شده در"),
        ),
        migrations.AlterField(
            model_name="location",
            name="updatedAt",
            field=models.DateTimeField(auto_now=True, verbose_name="آپدیت شده در"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="updatedAt",
            field=models.DateTimeField(auto_now=True, verbose_name="آپدیت شده در"),
        ),
        migrations.AlterField(
            model_name="review",
            name="updatedAt",
            field=models.DateTimeField(auto_now=True, verbose_name="آپدیت شده در"),
        ),
        migrations.AlterField(
            model_name="salon",
            name="updatedAt",
            field=models.DateTimeField(auto_now=True, verbose_name="آپدیت شده در"),
        ),
        migrations.AlterField(
            model_name="salonimage",
            name="updatedAt",
            field=models.DateTimeField(auto_now=True, verbose_name="آپدیت شده در"),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="updatedAt",
            field=models.DateTimeField(auto_now=True, verbose_name="آپدیت شده در"),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="updatedAt",
            field=models.DateTimeField(auto_now=True, verbose_name="آپدیت شده در"),
        ),
        migrations.CreateModel(
            name="SiteReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "createdAt",
                    models.DateTimeField(auto_now_add=True, verbose_name="ثبت شده در"),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(auto_now=True, verbose_name="آپدیت شده در"),
                ),
                ("text", models.TextField(verbose_name="نظر")),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
