# Generated by Django 4.2.4 on 2023-09-12 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("salon", "0003_alter_ordertime_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="availabletime",
            name="court",
        ),
        migrations.RemoveField(
            model_name="availabletime",
            name="times",
        ),
        migrations.AddField(
            model_name="availabletime",
            name="court",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="salon.court",
                verbose_name="نوع زمین ورزشی",
            ),
        ),
        migrations.AddField(
            model_name="availabletime",
            name="times",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="salon.timeslot",
                verbose_name="زمان",
            ),
        ),
    ]
