# Generated by Django 4.2.4 on 2023-09-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("salon", "0003_reservation_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="availabletime",
            name="court",
        ),
        migrations.AddField(
            model_name="availabletime",
            name="court",
            field=models.ManyToManyField(
                to="salon.court", verbose_name="نوع زمین ورزشی"
            ),
        ),
    ]
