# Generated by Django 4.2.4 on 2023-08-31 10:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("salon", "0004_alter_sitereview_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sitereview",
            old_name="User",
            new_name="user",
        ),
    ]
