# Generated by Django 4.2.4 on 2023-09-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("salon", "0005_rename_times_availabletime_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordertime",
            name="date",
        ),
        migrations.AddField(
            model_name="availabletime",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="تاریخ"),
        ),
    ]
