# Generated by Django 4.2.4 on 2023-09-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("salon", "0006_remove_ordertime_date_availabletime_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reserve",
            name="payment_number",
        ),
        migrations.AlterField(
            model_name="ordertime",
            name="qty",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
