# Generated by Django 4.2.4 on 2023-09-12 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("salon", "0007_remove_reserve_payment_number_alter_ordertime_qty"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "percent",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="درصد تخفیف"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "تخفیف\u200cها",
            },
        ),
        migrations.AddField(
            model_name="reserve",
            name="payment_number",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="شماره رزرو"
            ),
        ),
        migrations.CreateModel(
            name="MonthlyReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Sunday"),
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                        ],
                        verbose_name="روز هفته",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="تاریخ شروع")),
                ("end_date", models.DateField(verbose_name="تاریخ پایان")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "رزروهای ماهانه",
            },
        ),
        migrations.AddField(
            model_name="availabletime",
            name="discount",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="salon.discount",
                verbose_name="تخفیف",
            ),
        ),
        migrations.AddField(
            model_name="ordertime",
            name="monthly_reservation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="salon.monthlyreservation",
            ),
        ),
    ]
