# Generated by Django 4.2.4 on 2023-09-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("salon", "0008_discount_reserve_payment_number_monthlyreservation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="court",
            name="size",
            field=models.CharField(
                choices=[
                    ("SMALL", "SMALL"),
                    ("MEDIUM", "MEDIUM"),
                    ("LARGE", "LARGE"),
                    ("EXTRA_LARGE", "EXTRA_LARGE"),
                ],
                max_length=100,
                unique=True,
                verbose_name="اندازه زمین ورزشی",
            ),
        ),
        migrations.AlterField(
            model_name="monthlyreservation",
            name="day_of_week",
            field=models.IntegerField(
                choices=[
                    (0, "شنبه"),
                    (1, "یکشنبه"),
                    (2, "دوشنبه"),
                    (3, "سه شنبه"),
                    (4, "چهارشنبه"),
                    (5, "پنجشنبه"),
                    (6, "جمعه"),
                ],
                verbose_name="روز هفته",
            ),
        ),
        migrations.RemoveField(
            model_name="ordertime",
            name="available_time",
        ),
        migrations.AlterField(
            model_name="reserve",
            name="payment_method",
            field=models.CharField(
                blank=True,
                default="اینترنتی",
                max_length=200,
                null=True,
                verbose_name="نوع پرداخت",
            ),
        ),
        migrations.DeleteModel(
            name="CourtSize",
        ),
        migrations.AddField(
            model_name="ordertime",
            name="available_time",
            field=models.ManyToManyField(blank=True, to="salon.availabletime"),
        ),
    ]
