# Generated by Django 4.2.5 on 2024-02-14 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("salon", "0009_alter_court_size_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="court",
            name="size",
        ),
        migrations.RemoveField(
            model_name="salon",
            name="website",
        ),
    ]
