# Generated by Django 4.2.5 on 2024-02-14 11:30

from django.db import migrations, models
import django.db.models.deletion
import salon.models


class Migration(migrations.Migration):
    dependencies = [
        ("salon", "0010_remove_court_size_remove_salon_website"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordertime",
            name="monthly_reservation",
        ),
        migrations.AlterField(
            model_name="availabletime",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="تاریخ رزرو"),
        ),
        migrations.AlterField(
            model_name="court",
            name="salon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courts",
                to="salon.salon",
                verbose_name="سالن",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="salon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location",
                to="salon.salon",
                verbose_name="سالن",
            ),
        ),
        migrations.AlterField(
            model_name="salonimage",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=salon.models.salon_image_path,
                verbose_name="عکس",
            ),
        ),
        migrations.DeleteModel(
            name="MonthlyReservation",
        ),
    ]
