# Generated by Django 4.2.5 on 2024-03-07 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("salon", "0011_remove_ordertime_monthly_reservation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ball",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "createdAt",
                    models.DateTimeField(auto_now_add=True, verbose_name="ثبت شده در"),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(auto_now=True, verbose_name="آپدیت شده در"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0,
                        default=20000,
                        max_digits=15,
                        verbose_name="مبلغ اجاره توپ",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "اجاره توپ",
            },
        ),
        migrations.RemoveField(
            model_name="ordertime",
            name="qty",
        ),
        migrations.AlterField(
            model_name="ordertime",
            name="available_time",
            field=models.ManyToManyField(
                blank=True, related_name="time_reservations", to="salon.availabletime"
            ),
        ),
        migrations.AlterField(
            model_name="ordertime",
            name="price",
            field=models.DecimalField(
                decimal_places=0, max_digits=15, verbose_name="مبلغ"
            ),
        ),
        migrations.AlterField(
            model_name="ordertime",
            name="reserve",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_time_reservations",
                to="salon.reserve",
            ),
        ),
    ]
